name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select target environment'
        required: true
        type: choice
        options:
          - test
          - stage
          - prod

concurrency:
  group: deploy-${{ github.event.inputs.environment }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.environment }}
    runs-on: ubuntu-24.04
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Demo
        run: echo "FooBar"

